networks: 
  aplicacion_red:
    driver: bridge

services:
  aplicacion-postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: chema
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: aplicaciondb
      TZ: Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks: 
      - aplicacion_red

  aplicacion-flask:
    build: .
    image: aplicacion-flask
    container_name: aplicacion-flask
    depends_on:
      - aplicacion-postgres
    environment:
      DB_HOST: aplicacion-postgres
      DB_PORT: 5432
      DB_NAME: aplicaciondb
      DB_USER: chema
      DB_PASS: admin123
      TZ: Europe/Madrid
    ports:
      - "5010:5010"
    networks: 
      - aplicacion_red

  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      TZ: Europe/Madrid
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"      
    depends_on:
      - aplicacion-flask
    networks: 
      - aplicacion_red

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      TZ: Europe/Madrid
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - aplicacion-flask 
    networks: 
      - aplicacion_red

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      TZ: Europe/Madrid
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks: 
      - aplicacion_red
  
  loki:
    image: grafana/loki:2.9.0 
    environment:
      TZ: Europe/Madrid
    container_name: loki
    ports:
      - "3100:3100" 
    volumes:
      - ./loki.yml:/etc/loki/loki.yml:ro
      - loki_data:/loki 
    command: -config.file=/etc/loki/loki.yml -config.expand-env=true
    networks:
      - aplicacion_red

  promtail:
    image: grafana/promtail:2.9.0 
    container_name: promtail
    environment:
      TZ: Europe/Madrid
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - promtail_data:/var/promtail
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    depends_on:
      - loki 
    networks:
      - aplicacion_red

  grafana:
    image: grafana/grafana:10.4.2 
    container_name: grafana
    environment:
      TZ: Europe/Madrid
    ports:
      - "3000:3000" 
    volumes:
      - grafana_data:/var/lib/grafana 
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml 
    depends_on:
      - loki
      - prometheus 
    networks:
      - aplicacion_red

volumes:
  postgres_data:
  portainer_data:
  loki_data: 
  grafana_data: 
  prometheus_data:
  promtail_data: