version: "3.9"

networks: 
  aplicacion_red:
    driver: bridge

services:
  aplicacion-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: chema
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: aplicaciondb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks: 
      - aplicacion_red

  aplicacion-flask:
    build: .
    image: aplicacion-flask
    depends_on:
      - aplicacion-postgres
    environment:
      DB_HOST: aplicacion-postgres
      DB_PORT: 5432
      DB_NAME: aplicaciondb
      DB_USER: chema
      DB_PASS: admin123
    ports:
      - "5010:5010"
    networks: 
      - aplicacion_red

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"      
    depends_on:
      - aplicacion-flask
    networks: 
      - aplicacion_red

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - aplicacion-flask 
    networks: 
      - aplicacion_red

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks: #
      - aplicacion_red
  
  loki:
    image: grafana/loki:2.9.0 
    ports:
      - "3100:3100" 
    volumes:
      - loki_data:/loki 
    command: -config.file=/etc/loki/local-config.yaml 
    networks:
      - aplicacion_red

  promtail:
    image: grafana/promtail:2.9.0 
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki 
    networks:
      - aplicacion_red

  grafana:
    image: grafana/grafana:10.4.2 
    ports:
      - "3000:3000" 
    volumes:
      - grafana_data:/var/lib/grafana 
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml 
    depends_on:
      - loki
      - prometheus 
    networks:
      - aplicacion_red

volumes:
  postgres_data:
  portainer_data:
  loki_data: 
  grafana_data: 